server:
  port: 8888

spring:
  cloud:
    config:
      server:
        sweagle:
          scheme: https
          host: testing.sweagle.com
          port: 443
          export-format: json
          #username: demo
          #password: demoOnly
          #token: Basic XXX==
          token: XXX
          configdataset: spring-config
          parser: spring-demo
